name: Testerautorun

on: push

jobs:
  UnitTester:
    runs-on: ubuntu-latest
    steps: 
        - uses: actions/checkout@v2
        - name: Installing 
            run: sudo apt install libgtest-dev && sudo apt install cmake && cd /usr/src/gtest && sudo cmake . && sudo make && sudo cp *.a /usr/lib && sudo ln -s /usr/lib/libgtest.a /usr/local/lib/libgtest.a && sudo ln -s /usr/lib/libgtest_main.a /usr/local/lib/libgtest_main.a
          
        - run: cd test
        - name: Test
            run: sudo cmake CMakeLists.txt && sudo make && ./runTests

      