name: Test workflow

on: push

jobs:

  static_code_analysis:
    runs-on: ubuntu-latest
    container: csibe1999/mosze
    steps:
      - uses: actions/checkout@v2

      - run: make static_code_analysis

      - uses: actions/upload-artifact@v2
        with:
          name: Static_code_analysis_artifact
          path: ./static-code-analysis.txt

  build_test_and_memory_leak_check:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2

      - run: make build

      - run: make buildtest

      - run: make memory_leak_check

      - uses: actions/upload-artifact@v2
        with:
          name: Memory_leak_check_artifact
          path: ./memory-leak-check.txt

