name: Testerautorun

on: push

jobs:
  UnitTester:
    runs-on: ubuntu-latest
    container: csibe1999/mosze:latest
    steps:
      - uses: actions/checkout@v2
            
      - name: Running
        run: make unittest