name: Test workflow

on: push

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2
      - run: g++ -Wall *.cpp
      - run: chmod +x test.sh
      - run: ./test.sh
