name: Test workflow

on:
  push

jobs:

  static_code_analysis:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2

      - run: sudo apt-get install cppcheck
      - run: chmod +x static-code-analysis.sh
      - run: ./static-code-analysis.sh

      - uses: actions/upload-artifact@v2
        with:
          name: Static_code_analysis_artifact
          path: ./static-code-analysis.txt

  build_test_and_memory_leak_check:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2

      - run: g++ -Wall -Wextra -Werror *.cpp

      - run: chmod +x test.sh
      - run: ./test.sh

      - run: sudo apt-get install valgrind
      - run: chmod +x memory-leak-check.sh
      - run: ./memory-leak-check.sh

      - uses: actions/upload-artifact@v2
        with:
          name: Memory_leak_check_artifact
          path: ./memory-leak-check.txt