name: Testerautorun

on: push

jobs:
  UnitTester:
    runs-on: ubuntu-latest
    steps: 
        - uses: actions/checkout@v2
        - name: Installing 
            run: sudo apt install libgtest-dev && sudo apt install cmake

        - run: cd /usr/src/gtest
        - run: sudo ln -st /usr/lib/ /usr/src/gtest/libgtest.a
        - run: sudo ln -st /usr/lib/ /usr/src/gtest/libgtest_main.a
          
        - run: cd test
        - name: Test
            run: sudo cmake CMakeLists.txt && sudo make && ./runTests

      